config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    get "search", to: "searches#search"
    get 'likes', to: 'likes#index', as: 'liked_posts'
    get 'feed', to: 'posts#feed', as: 'feed'

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy] 
    end

    resources :lost_pets do
      resources :lost_pet_comments, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :followings
        get :followers
      end
    end

    resources :relationships, only: [:create, :destroy]
    resources :tags, only: [:show, :index]
    resources :lost_pet_tags, only: [:show, :index]
  end


  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :introduction, length: { maximum: 500 } 

  def guest_user?
    email == "guest@example.com"
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
      user.introduction = 'ゲストとしてログインしています。'
    end
  end

  def follow(other_user)
    return if self == other_user
    active_relationships.find_or_create_by(followed_id: other_user.id)
  end

  def unfollow(other_user)
    relationship = active_relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def feed
    Post.where(user_id: followings.select(:id)).or(Post.where(user_id: self.id))
  end
  

  has_one_attached :avatar
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :lost_pets, dependent: :destroy
  has_many :lost_pet_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all

    if params[:query].present?
      @users = @users.where("name LIKE ? OR email LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end
  
    if params[:status].present?
      @users = @users.where(is_active: params[:status] == 'true')
    end
  end

  def show
  end

  def edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'ユーザー情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @user.update(is_active: false)
    redirect_to admin_users_path, notice: 'ユーザーは退会しました。'
  end 
end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_sign_up_path_for(resource)
    posts_path 
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) 
    devise_parameter_sanitizer.permit(:account_update, keys: [:name]) 
  end
end

app/controllers/users/sessions_controller.rb
# app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  protected

  def after_sign_in_path_for(resource)
    posts_path 
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2 class="mb-4"><%= @user.name %> さんの会員情報編集</h2>

<%= form_with(model: @user, url: admin_user_path(@user), method: :patch, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :is_active, "会員ステータス" %>
    <%= f.select :is_active, [['有効', true], ['退会', false]], class: "form-control" %>
  </div>

  <div class="d-flex ms-4">
    <%= f.submit '保存', class: 'btn btn-primary', style: 'margin-right: 10px;' %>
    <%= link_to '戻る', admin_users_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h2 class="mb-4">会員一覧</h2>

<%= form_with(url: admin_users_path, method: :get, local: true, class: "d-flex justify-content-end mb-3") do %>
  <%= text_field_tag :query, params[:query], class: "form-control me-2", placeholder: "名前またはメールで検索...", style: "max-width: 350px;" %>
  <%= select_tag :status, options_for_select([['全て', ''], ['有効', 'true'], ['退会', 'false']], params[:status]), 
                 class: "form-control me-2", style: "max-width: 150px;" %>
  
  <%= button_tag "検索", type: :submit, class: "btn btn-outline-primary" %>
<% end %>

<% if @users.any? %> 
  <table class="table table-striped table-hover align-middle">
    <thead class="table-light">
      <tr>
        <th>会員ID</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>登録日</th>
        <th>会員ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td> 
          <td>
            <%= link_to user.name, admin_user_path(user), class: 'text-decoration-none' %>
          </td>
          <td><%= user.email %></td>
          <td><%= user.created_at.strftime('%Y-%m-%d') %></td>
          <td>
            <% if user.is_active %>
              <span class="text-success font-weight-bold">有効</span>
            <% else %>
              <span class="text-danger font-weight-bold">退会</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-muted">検索結果はありません。</p>
<% end %>

app/views/admin/users/show.html.erb
<h2 class="mb-4"><%= @user.name %> さんの会員詳細</h2>

  <div class="row mb-3">
    <div class="col-md-2">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar.variant(resize: "100x100"), class: "rounded-circle", alt: @user.name %>
      <% else %>
        <p>プロフィール画像なし</p>
      <% end %>
    </div>

    <div class="col-md-10">
      <table class="table table-sm table-borderless align-middle">
        <tbody>
          <tr>
            <th style="width: 120px;">会員ID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th style="width: 200px;">メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th style="width: 200px;">登録日</th>
            <td><%= @user.created_at.strftime('%Y-%m-%d') %></td>
          </tr>
          <tr>
            <th style="width: 200px;">会員ステータス</th>
            <td>
              <% if @user.is_active %>
                <span class="text-success font-weight-bold">有効</span>
              <% else %>
                <span class="text-danger font-weight-bold">退会</span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="d-flex ">
    <%= link_to '編集', edit_admin_user_path(@user), class: 'btn btn-primary', style: 'margin-right: 10px;' %>
    <%= link_to '戻る', admin_users_path, class: 'btn btn-secondary' %>
  </div>